name: Validate Vocabs on PRs to Master
on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ','
