name: Push updated vocabs
on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ','        
      - name: detect file changes
        run: |
          echo 'files modified:'            
          echo '${{steps.file_changes.outputs.files_modified}}'
          echo 'files added:'            
          echo '${{steps.file_changes.outputs.files_added}}'
          echo 'files removed:'            
          echo '${{steps.file_changes.outputs.files_removed}}'
          
          for name in ${steps.file_changes.outputs.files_modified} do
            echo $name "\n"
          done
          
          echo "\n\n"
          
          for name in ${steps.file_changes.outputs.files_added} do
            echo $name "\n"
          done          
