name: Handle updated vocabs
on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ','        
      - name: detect file changes
        env:
            DB_USERNAME: ${{secrets.DB_USERNAME}}
            DB_PASSWORD: ${{secrets.DB_PASSWORD}}      
        run: |
          echo 'Run update script...'
          if [[ ${{steps.file_changes.outputs.files_added}} ]]; then a=${{steps.file_changes.outputs.files_added}}; else a=""; fi
          if [[ ${{steps.file_changes.outputs.files_modified}} ]]; then m=${{steps.file_changes.outputs.files_modified}}; else m=""; fi
          if [[ ${{steps.file_changes.outputs.files_removed}} ]]; then r=${{steps.file_changes.outputs.files_removed}}; else r=""; fi
          echo 'python scripts/update_vocabs.py -a $a -m $m -r $r'
