name: Handle updated vocabs
on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ','        
      - name: detect file changes
        env:
            DB_USERNAME: ${{secrets.DB_USERNAME}}
            DB_PASSWORD: ${{secrets.DB_PASSWORD}}      
        run: |
          echo 'Run update script...'
          if [[ -z ${{steps.file_changes.outputs.files_added}} ]]; then a=""; else a=${{steps.file_changes.outputs.files_added}}; fi
          if [[ -z ${{steps.file_changes.outputs.files_modified}} ]]; then m=""; else m=${{steps.file_changes.outputs.files_modified}}; fi
          if [[ -z ${{steps.file_changes.outputs.files_removed}} ]]; then r=""; else r=${{steps.file_changes.outputs.files_removed}}; fi
          echo 'python scripts/update_vocabs.py -a $a -m $m -r $r'
